In [1]:
import pandas as pd
import os

In [2]:
census_file = os.path.join("..", "data", "census-csv", "acs2017_county_data.csv")

In [3]:
census_df = pd.read_csv(census_file)
census_df.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

In [4]:
print(census_df.columns)
print(census_df.dtypes)
print(census_df.shape)

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')
CountyId              int64
State                object
County               object
TotalPop              int64
Men                   int64
Women                 int64
Hispanic            float64
White               float64
Black               float64
Native              float64
Asian               float64
Pacific             float64
VotingAgeCitizen      int64
Income                int64
IncomeErr             int64
IncomePerCap          int64
IncomePerCapErr       int64
Poverty             float64
ChildPoverty        float64
Professional        float64
Service             float64
Office              float64
Construction        float64
Production          float64
Drive               float64
Carpool             float64
Transit             float64
Walk                float64
OtherTransp         float64
WorkAtHome          float64
MeanCommute         float64
Employed              int64
PrivateWork         float64
PublicWork          float64
SelfEmployed        float64
FamilyWork          float64
Unemployment        float64
dtype: object
(3220, 37)

In [5]:
census_df['County']=census_df['County'].apply(lambda x: x.strip())
census_df

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Puerto Rico,Vega Baja Municipio,54754,26269,28485,96.7,3.1,0.1,0.0,...,1.4,0.6,0.9,31.6,14234,76.2,19.3,4.3,0.2,16.8
3216,72147,Puerto Rico,Vieques Municipio,8931,4351,4580,95.7,4.0,0.0,0.0,...,5.0,0.0,1.7,14.9,2927,40.7,40.9,18.4,0.0,12.8
3217,72149,Puerto Rico,Villalba Municipio,23659,11510,12149,99.7,0.2,0.1,0.0,...,2.1,0.0,2.8,28.4,6873,59.2,30.2,10.4,0.2,24.8
3218,72151,Puerto Rico,Yabucoa Municipio,35025,16984,18041,99.9,0.1,0.0,0.0,...,1.4,1.8,0.1,30.5,7878,62.7,30.9,6.3,0.0,25.4
3219,72153,Puerto Rico,Yauco Municipio,37585,18052,19533,99.8,0.2,0.0,0.0,...,1.7,0.1,5.0,24.4,8995,66.4,28.7,5.0,0.0,24.0

In [6]:
condensed_census = ['State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'IncomePerCap', 'Professional', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Unemployment']
condensed_census_df = census_df[condensed_census]
condensed_census_df.head()

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,IncomePerCap,Professional,Walk,OtherTransp,WorkAtHome,MeanCommute,Unemployment
0,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,0.9,0.0,27824,35.3,0.6,1.3,2.5,25.8,5.2
1,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,0.7,0.0,29364,35.7,0.8,1.1,5.6,27.0,5.5
2,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,0.6,0.0,17561,25.0,2.2,1.7,1.3,23.4,12.4
3,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,0.0,0.0,20911,24.4,0.3,1.7,1.5,30.0,8.2
4,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,0.1,0.0,22021,28.5,0.4,0.4,2.1,35.0,4.9

In [8]:
#states = ["Texas", "Florida", "California", 'District of Columbia', 'New York']
#counties = ['Alameda County', 'Albany County','Austin County','Bexar County', 'Broward County',
            #'Dallas County', 'District of Columbia', 'Duval County', 'Erie County', 'Escambia County',
            #'Harris County', 'Hillsborough County', 'Los Angeles County', 'Monroe County', 'New York County',
           #'Pinellas Count', 'San Diego County','San Francisco County','Tarrant County']
#census_byAbnbstate = condensed_census_df.loc[condensed_census_df['State']=="Texas", "Florida", "California", 'District of Columbia', 'New York']
census_byAbnbstate = condensed_census_df[(condensed_census_df['State'] == "Texas")| 
                                         (condensed_census_df['State'] =="Florida")| 
                                         (condensed_census_df['State'] =="California")|
                                         (condensed_census_df['State'] =='District of Columbia')|
                                         (condensed_census_df['State'] == 'New York')]
census_byAbnbstate

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,IncomePerCap,Professional,Walk,OtherTransp,WorkAtHome,MeanCommute,Unemployment
186,California,Alameda County,1629615,799649,829966,22.5,32.2,10.7,0.3,28.7,0.8,41363,48.0,3.7,3.6,6.0,32.5,6.0
187,California,Alpine County,1203,664,539,9.7,64.6,1.5,20.6,0.7,0.0,27448,38.2,9.1,1.6,14.0,21.9,14.6
188,California,Amador County,37306,20005,17301,13.2,79.3,2.0,0.7,1.5,0.2,29628,32.7,2.5,1.1,6.4,32.0,9.3
189,California,Butte County,225207,111587,113620,15.7,72.9,1.5,0.7,4.4,0.2,26304,35.9,3.2,3.9,5.7,20.1,9.1
190,California,Calaveras County,45057,22292,22765,11.5,82.0,0.6,0.9,1.2,0.5,31652,35.6,1.2,0.6,8.3,35.5,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2772,Texas,Wood County,43315,21523,21792,9.6,83.2,5.5,0.6,0.1,0.1,25955,28.7,2.5,1.0,5.6,30.2,7.8
2773,Texas,Yoakum County,8481,4286,4195,65.0,33.2,0.0,0.2,0.0,0.0,23681,21.8,3.7,0.2,1.3,16.2,7.5
2774,Texas,Young County,18166,8922,9244,18.1,78.8,1.5,0.5,0.4,0.0,25661,31.5,0.6,1.4,6.1,15.3,4.5
2775,Texas,Zapata County,14415,7190,7225,94.1,5.2,0.0,0.0,0.7,0.0,17817,17.7,4.4,0.6,2.0,18.2,12.4
2776,Texas,Zavala County,12152,6163,5989,93.6,5.4,0.5,0.1,0.0,0.0,13105,29.0,2.1,4.2,5.4,13.7,10.1

In [9]:
#["Bexar", "Travis", "Tarrant", "Dallas", "Harris", "Alameda", "Los Angeles", 
#"San Francisco", "San Diego", "Broward", "Duval", "Hillsborough", 
#"Escambia", "Pinellas", "New York", "Kings", "Erie", "Monroe County", 
#"Albany", "Onondaga", "District of Columbia"]
census_byAbnbcounty = census_byAbnbstate[(census_byAbnbstate['County'] == 'Alameda County')| 
                                         (census_byAbnbstate['County'] =='Albany County')| 
                                         (census_byAbnbstate['County'] =='Austin County')|
                                         (census_byAbnbstate['County'] =='Bexar County')|
                                         (census_byAbnbstate['County'] =='Broward County' )|
                                        (census_byAbnbstate['County'] =='Dallas County')|
                                        (census_byAbnbstate['County'] =='District of Columbia')|
                                        (census_byAbnbstate['County'] =='Duval County')|
                                        (census_byAbnbstate['County'] =='Erie County')|
                                        (census_byAbnbstate['County'] =='Escambia County')|
                                        (census_byAbnbstate['County'] =='Harris County')|
                                        (census_byAbnbstate['County'] =='Hillsborough County')|
                                        (census_byAbnbstate['County'] =='Los Angeles County')|
                                        (census_byAbnbstate['County'] =='Monroe County')|
                                        (census_byAbnbstate['County'] =='New York County')|
                                        (census_byAbnbstate['County'] =='Pinellas County')|
                                        (census_byAbnbstate['County'] =='San Diego County')|
                                        (census_byAbnbstate['County'] =='San Francisco County')|
                                        (census_byAbnbstate['County'] =='Tarrant County')|
                                        (census_byAbnbstate['County'] =='Travis County')|
                                        (census_byAbnbstate['County'] =='Onondaga County')]
                                        
census_byAbnbcounty.head()

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,IncomePerCap,Professional,Walk,OtherTransp,WorkAtHome,MeanCommute,Unemployment
186,California,Alameda County,1629615,799649,829966,22.5,32.2,10.7,0.3,28.7,0.8,41363,48.0,3.7,3.6,6.0,32.5,6.0
204,California,Los Angeles County,10105722,4979641,5126081,48.4,26.5,7.9,0.2,14.3,0.2,30798,36.4,2.7,2.3,5.3,30.9,7.8
222,California,San Diego County,3283665,1651147,1632518,33.4,46.2,4.7,0.4,11.5,0.4,34350,41.3,2.9,2.2,7.0,25.7,7.1
223,California,San Francisco County,864263,440633,423630,15.3,40.8,5.1,0.2,33.9,0.3,59508,55.0,11.1,7.1,6.7,32.8,5.4
319,District of Columbia,District of Columbia,672391,319046,353345,10.7,36.0,46.9,0.2,3.7,0.0,50832,61.7,13.2,6.2,5.7,30.0,8.0

In [10]:
census_byAbnbcounty.to_csv(os.path.join("..", "data", "census-csv", "census_bycounty.csv"))

In [11]:
crime_file = os.path.join("..", "data", "crime_county-csv", "crime_data_w_population_and_crime_rate.csv")

In [12]:
crime_df = pd.read_csv(crime_file)
crime_df.head()

,county_name,crime_rate_per_100000,index,EDITION,PART,IDNO,CPOPARST,CPOPCRIM,AG_ARRST,AG_OFF,...,RAPE,ROBBERY,AGASSLT,BURGLRY,LARCENY,MVTHEFT,ARSON,population,FIPS_ST,FIPS_CTY
0,"St. Louis city, MO",1791.995377,1,1,4,1612,318667,318667,15,15,...,200,1778,3609,4995,13791,3543,464,318416,29,510
1,"Crittenden County, AR",1754.914968,2,1,4,130,50717,50717,4,4,...,38,165,662,1482,1753,189,28,49746,5,35
2,"Alexander County, IL",1664.700485,3,1,4,604,8040,8040,2,2,...,2,5,119,82,184,12,2,7629,17,3
3,"Kenedy County, TX",1456.310680,4,1,4,2681,444,444,1,1,...,3,1,2,5,4,4,0,412,48,261
4,"De Soto Parish, LA",1447.402430,5,1,4,1137,26971,26971,3,3,...,4,17,368,149,494,60,0,27083,22,31

In [13]:
print(crime_df.columns)
print(crime_df.dtypes)
print(crime_df.shape)

Index(['county_name', 'crime_rate_per_100000', 'index', 'EDITION', 'PART',
       'IDNO', 'CPOPARST', 'CPOPCRIM', 'AG_ARRST', 'AG_OFF', 'COVIND', 'INDEX',
       'MODINDX', 'MURDER', 'RAPE', 'ROBBERY', 'AGASSLT', 'BURGLRY', 'LARCENY',
       'MVTHEFT', 'ARSON', 'population', 'FIPS_ST', 'FIPS_CTY'],
      dtype='object')
county_name               object
crime_rate_per_100000    float64
index                      int64
EDITION                    int64
PART                       int64
IDNO                       int64
CPOPARST                   int64
CPOPCRIM                   int64
AG_ARRST                   int64
AG_OFF                     int64
COVIND                   float64
INDEX                      int64
MODINDX                    int64
MURDER                     int64
RAPE                       int64
ROBBERY                    int64
AGASSLT                    int64
BURGLRY                    int64
LARCENY                    int64
MVTHEFT                    int64
ARSON                      int64
population                 int64
FIPS_ST                    int64
FIPS_CTY                   int64
dtype: object
(3136, 24)

In [14]:
condensed_crime = ['county_name', 'crime_rate_per_100000', 'MURDER', 'RAPE', 'ROBBERY', 'AGASSLT', 'BURGLRY', 'LARCENY',
       'MVTHEFT', 'ARSON']
condensed_crime_df = crime_df[condensed_crime]
condensed_crime_df.head()

,county_name,crime_rate_per_100000,MURDER,RAPE,ROBBERY,AGASSLT,BURGLRY,LARCENY,MVTHEFT,ARSON
0,"St. Louis city, MO",1791.995377,119,200,1778,3609,4995,13791,3543,464
1,"Crittenden County, AR",1754.914968,8,38,165,662,1482,1753,189,28
2,"Alexander County, IL",1664.700485,1,2,5,119,82,184,12,2
3,"Kenedy County, TX",1456.310680,0,3,1,2,5,4,4,0
4,"De Soto Parish, LA",1447.402430,3,4,17,368,149,494,60,0

In [15]:
condensed_crime_df.rename(columns={'county_name' : "County", 'crime_rate_per_100000' : 'Crime_RatePer100K', 
                                   'MURDER': 'Murder', 'RAPE': 'Rape', 'ROBBERY' : 'Robbery', 'AGASSLT' : 'Agg.Assault',
                                   'BURGLRY': 'Burglary', 'LARCENY':'Larceny', 'MVTHEFT': 'MotorVeh Theft', 'ARSON':'Arson', 
                                   'population' : 'Population'}, inplace =True)

condensed_crime_df.head()

c:\python38\lib\site-packages\pandas\core\frame.py:4295: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,County,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
0,"St. Louis city, MO",1791.995377,119,200,1778,3609,4995,13791,3543,464
1,"Crittenden County, AR",1754.914968,8,38,165,662,1482,1753,189,28
2,"Alexander County, IL",1664.700485,1,2,5,119,82,184,12,2
3,"Kenedy County, TX",1456.310680,0,3,1,2,5,4,4,0
4,"De Soto Parish, LA",1447.402430,3,4,17,368,149,494,60,0

In [16]:
crime_byAbnbcounty = condensed_crime_df[(condensed_crime_df['County'] == 'Alameda County, CA')| 
                                         (condensed_crime_df['County'] =='Albany County, NY')| 
                                         (condensed_crime_df['County'] =='Austin County, TX')|
                                         (condensed_crime_df['County'] =='Bexar County, TX')|
                                         (condensed_crime_df['County'] =='Broward County, FL' )|
                                        (condensed_crime_df['County'] =='Dallas County, TX')|
                                        (condensed_crime_df['County'] =='District of Columbia, DC')|
                                        (condensed_crime_df['County'] =='Duval County, FL')|
                                        (condensed_crime_df['County'] =='Erie County, NY')|
                                        (condensed_crime_df['County'] =='Escambia County, FL')|
                                        (condensed_crime_df['County'] =='Harris County, TX')|
                                        (condensed_crime_df['County'] =='Hillsborough County, FL')|
                                        (condensed_crime_df['County'] =='Los Angeles County, CA')|
                                        (condensed_crime_df['County'] =='Monroe County, NY')|
                                        (condensed_crime_df['County'] =='New York County, NY')|
                                        (condensed_crime_df['County'] =='Pinellas County, FL')|
                                        (condensed_crime_df['County'] =='San Diego County, CA')|
                                        (condensed_crime_df['County'] =='San Francisco County, CA')|
                                        (condensed_crime_df['County'] =='Tarrant County, TX')|
                                        (condensed_crime_df['County'] =='Travis County, TX')|
                                        (condensed_crime_df['County'] =='Onondaga County, NY')]
                                        
crime_byAbnbcounty.head()

,County,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
9,"District of Columbia, DC",1216.801325,88,236,4037,3505,3519,23575,3663,51
57,"Escambia County, FL",798.516760,22,162,502,1756,3899,9920,680,52
71,"Alameda County, CA",753.693574,153,477,6220,5050,13245,35841,13044,337
90,"San Francisco County, CA",701.421710,69,110,3554,2141,5401,29256,5381,211
93,"Harris County, TX",696.103834,307,1143,12449,16290,43644,114208,20829,1153

In [23]:
crime_byAbnbcounty['County'] = crime_byAbnbcounty['County'].apply(lambda x: pd.Series(x.split(',')))
crime_byAbnbcounty

<ipython-input-23-f247292aa47b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crime_byAbnbcounty['County'] = crime_byAbnbcounty['County'].apply(lambda x: pd.Series(x.split(',')))

,County,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
9,District of Columbia,1216.801325,88,236,4037,3505,3519,23575,3663,51
57,Escambia County,798.516760,22,162,502,1756,3899,9920,680,52
71,Alameda County,753.693574,153,477,6220,5050,13245,35841,13044,337
90,San Francisco County,701.421710,69,110,3554,2141,5401,29256,5381,211
93,Harris County,696.103834,307,1143,12449,16290,43644,114208,20829,1153
130,New York County,634.009343,81,227,3932,6070,3623,22730,1592,0
142,Duval County,621.546416,94,355,1436,3621,8025,27335,1712,96
233,Pinellas County,550.671225,44,361,1206,3505,7392,24499,1755,167
352,Broward County,470.948052,80,401,3408,4771,17400,45279,4320,180
370,Erie County,459.306029,50,211,1602,2361,6019,19729,1481,341
396,Los Angeles County,444.800814,600,1976,18923,23057,49107,142604,40555,2210
404,Dallas County,442.965072,165,706,4889,5227,25141,59144,10235,692
432,Bexar County,431.060568,101,649,2038,5047,18580,69589,7155,336
467,Tarrant County,416.156389,73,687,2167,5028,16077,46906,4559,228
586,Onondaga County,374.903659,15,111,539,1091,2988,8553,592,63
605,San Diego County,368.672406,107,692,3200,7840,14076,43412,12136,346
652,Monroe County,356.854134,41,175,1011,1447,4968,16774,976,233
661,Hillsborough County,353.830740,53,187,1130,3200,7139,21548,1811,110
687,Travis County,345.420062,32,236,997,2607,8244,36913,2419,152
749,Albany County,330.678134,5,69,318,623,1497,7210,265,19
1497,Austin County,194.127639,1,7,5,43,142,322,27,1

In [17]:
crime_byAbnbcounty.to_csv(os.path.join("..", "data", "census-csv", "crime_bycounty.csv"))

In [18]:
census_crime_merge = pd.merge(census_byAbnbcounty,crime_byAbnbcounty, on="County", how ="outer" )
census_crime_merge

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Unemployment,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
0,California,Alameda County,1629615.0,799649.0,829966.0,22.5,32.2,10.7,0.3,28.7,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,California,Los Angeles County,10105722.0,4979641.0,5126081.0,48.4,26.5,7.9,0.2,14.3,...,7.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,California,San Diego County,3283665.0,1651147.0,1632518.0,33.4,46.2,4.7,0.4,11.5,...,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,California,San Francisco County,864263.0,440633.0,423630.0,15.3,40.8,5.1,0.2,33.9,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,District of Columbia,District of Columbia,672391.0,319046.0,353345.0,10.7,36.0,46.9,0.2,3.7,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Florida,Broward County,1890416.0,920265.0,970151.0,28.4,38.2,27.4,0.2,3.5,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Florida,Duval County,912043.0,442115.0,469928.0,9.0,54.1,29.3,0.2,4.6,...,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Texas,Duval County,11434.0,5891.0,5543.0,89.3,9.0,1.4,0.0,0.3,...,13.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Florida,Escambia County,309924.0,153834.0,156090.0,5.5,64.8,21.6,0.4,2.8,...,7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Florida,Hillsborough County,1351087.0,658639.0,692448.0,27.4,50.3,15.5,0.2,3.9,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Florida,Monroe County,76745.0,40218.0,36527.0,23.5,67.3,6.7,0.1,1.2,...,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,New York,Monroe County,748680.0,361649.0,387031.0,8.3,71.0,14.5,0.2,3.6,...,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Florida,Pinellas County,949842.0,456017.0,493825.0,9.2,74.7,10.0,0.2,3.3,...,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,New York,Albany County,308580.0,149287.0,159293.0,5.7,73.0,11.7,0.1,6.4,...,5.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,New York,Erie County,923995.0,447024.0,476971.0,5.2,76.0,13.0,0.4,3.4,...,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,New York,New York County,1653877.0,782142.0,871735.0,26.1,46.8,12.5,0.1,11.9,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,New York,Onondaga County,467669.0,225685.0,241984.0,4.7,77.1,10.7,0.5,3.9,...,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Texas,Austin County,29292.0,14474.0,14818.0,25.9,63.3,8.9,0.0,0.2,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Texas,Bexar County,1892004.0,932577.0,959427.0,59.8,28.4,7.0,0.2,2.6,...,6.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Texas,Dallas County,2552213.0,1257751.0,1294462.0,39.6,30.2,22.1,0.2,6.0,...,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Texas,Harris County,4525519.0,2251060.0,2274459.0,42.2,30.6,18.5,0.2,6.8,...,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Texas,Tarrant County,1983675.0,971142.0,1012533.0,28.2,48.3,15.6,0.3,5.1,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Texas,Travis County,1176584.0,593319.0,583265.0,33.9,49.3,7.9,0.2,6.3,...,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,"District of Columbia, DC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1216.801325,88.0,236.0,4037.0,3505.0,3519.0,23575.0,3663.0,51.0
24,NaN,"Escambia County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,798.516760,22.0,162.0,502.0,1756.0,3899.0,9920.0,680.0,52.0
25,NaN,"Alameda County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,753.693574,153.0,477.0,6220.0,5050.0,13245.0,35841.0,13044.0,337.0
26,NaN,"San Francisco County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,701.421710,69.0,110.0,3554.0,2141.0,5401.0,29256.0,5381.0,211.0
27,NaN,"Harris County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,696.103834,307.0,1143.0,12449.0,16290.0,43644.0,114208.0,20829.0,1153.0
28,NaN,"New York County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,634.009343,81.0,227.0,3932.0,6070.0,3623.0,22730.0,1592.0,0.0
29,NaN,"Duval County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,621.546416,94.0,355.0,1436.0,3621.0,8025.0,27335.0,1712.0,96.0
30,NaN,"Pinellas County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,550.671225,44.0,361.0,1206.0,3505.0,7392.0,24499.0,1755.0,167.0
31,NaN,"Broward County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,470.948052,80.0,401.0,3408.0,4771.0,17400.0,45279.0,4320.0,180.0
32,NaN,"Erie County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,459.306029,50.0,211.0,1602.0,2361.0,6019.0,19729.0,1481.0,341.0
33,NaN,"Los Angeles County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,444.800814,600.0,1976.0,18923.0,23057.0,49107.0,142604.0,40555.0,2210.0
34,NaN,"Dallas County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,442.965072,165.0,706.0,4889.0,5227.0,25141.0,59144.0,10235.0,692.0
35,NaN,"Bexar County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,431.060568,101.0,649.0,2038.0,5047.0,18580.0,69589.0,7155.0,336.0
36,NaN,"Tarrant County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,416.156389,73.0,687.0,2167.0,5028.0,16077.0,46906.0,4559.0,228.0
37,NaN,"Onondaga County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,374.903659,15.0,111.0,539.0,1091.0,2988.0,8553.0,592.0,63.0
38,NaN,"San Diego County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,368.672406,107.0,692.0,3200.0,7840.0,14076.0,43412.0,12136.0,346.0
39,NaN,"Monroe County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,356.854134,41.0,175.0,1011.0,1447.0,4968.0,16774.0,976.0,233.0
40,NaN,"Hillsborough County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,353.830740,53.0,187.0,1130.0,3200.0,7139.0,21548.0,1811.0,110.0
41,NaN,"Travis County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,345.420062,32.0,236.0,997.0,2607.0,8244.0,36913.0,2419.0,152.0
42,NaN,"Albany County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,330.678134,5.0,69.0,318.0,623.0,1497.0,7210.0,265.0,19.0
43,NaN,"Austin County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,194.127639,1.0,7.0,5.0,43.0,142.0,322.0,27.0,1.0

In [19]:
census_crime_merge.set_index('State')

,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,...,Unemployment,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
State,,,,,,,,,,,,,,,,,,,,,
California,Alameda County,1629615.0,799649.0,829966.0,22.5,32.2,10.7,0.3,28.7,0.8,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
California,Los Angeles County,10105722.0,4979641.0,5126081.0,48.4,26.5,7.9,0.2,14.3,0.2,...,7.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
California,San Diego County,3283665.0,1651147.0,1632518.0,33.4,46.2,4.7,0.4,11.5,0.4,...,7.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
California,San Francisco County,864263.0,440633.0,423630.0,15.3,40.8,5.1,0.2,33.9,0.3,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
District of Columbia,District of Columbia,672391.0,319046.0,353345.0,10.7,36.0,46.9,0.2,3.7,0.0,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,Broward County,1890416.0,920265.0,970151.0,28.4,38.2,27.4,0.2,3.5,0.0,...,7.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,Duval County,912043.0,442115.0,469928.0,9.0,54.1,29.3,0.2,4.6,0.1,...,7.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,Duval County,11434.0,5891.0,5543.0,89.3,9.0,1.4,0.0,0.3,0.0,...,13.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,Escambia County,309924.0,153834.0,156090.0,5.5,64.8,21.6,0.4,2.8,0.1,...,7.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,Hillsborough County,1351087.0,658639.0,692448.0,27.4,50.3,15.5,0.2,3.9,0.1,...,6.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,Monroe County,76745.0,40218.0,36527.0,23.5,67.3,6.7,0.1,1.2,0.0,...,3.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New York,Monroe County,748680.0,361649.0,387031.0,8.3,71.0,14.5,0.2,3.6,0.0,...,6.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Florida,Pinellas County,949842.0,456017.0,493825.0,9.2,74.7,10.0,0.2,3.3,0.1,...,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New York,Albany County,308580.0,149287.0,159293.0,5.7,73.0,11.7,0.1,6.4,0.0,...,5.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New York,Erie County,923995.0,447024.0,476971.0,5.2,76.0,13.0,0.4,3.4,0.0,...,5.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New York,New York County,1653877.0,782142.0,871735.0,26.1,46.8,12.5,0.1,11.9,0.0,...,6.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New York,Onondaga County,467669.0,225685.0,241984.0,4.7,77.1,10.7,0.5,3.9,0.0,...,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,Austin County,29292.0,14474.0,14818.0,25.9,63.3,8.9,0.0,0.2,0.0,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,Bexar County,1892004.0,932577.0,959427.0,59.8,28.4,7.0,0.2,2.6,0.1,...,6.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,Dallas County,2552213.0,1257751.0,1294462.0,39.6,30.2,22.1,0.2,6.0,0.0,...,5.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,Harris County,4525519.0,2251060.0,2274459.0,42.2,30.6,18.5,0.2,6.8,0.1,...,6.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,Tarrant County,1983675.0,971142.0,1012533.0,28.2,48.3,15.6,0.3,5.1,0.2,...,5.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Texas,Travis County,1176584.0,593319.0,583265.0,33.9,49.3,7.9,0.2,6.3,0.0,...,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,"District of Columbia, DC",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1216.801325,88.0,236.0,4037.0,3505.0,3519.0,23575.0,3663.0,51.0
NaN,"Escambia County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,798.516760,22.0,162.0,502.0,1756.0,3899.0,9920.0,680.0,52.0
NaN,"Alameda County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,753.693574,153.0,477.0,6220.0,5050.0,13245.0,35841.0,13044.0,337.0
NaN,"San Francisco County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,701.421710,69.0,110.0,3554.0,2141.0,5401.0,29256.0,5381.0,211.0
NaN,"Harris County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,696.103834,307.0,1143.0,12449.0,16290.0,43644.0,114208.0,20829.0,1153.0
NaN,"New York County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,634.009343,81.0,227.0,3932.0,6070.0,3623.0,22730.0,1592.0,0.0
NaN,"Duval County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,621.546416,94.0,355.0,1436.0,3621.0,8025.0,27335.0,1712.0,96.0
NaN,"Pinellas County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,550.671225,44.0,361.0,1206.0,3505.0,7392.0,24499.0,1755.0,167.0
NaN,"Broward County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,470.948052,80.0,401.0,3408.0,4771.0,17400.0,45279.0,4320.0,180.0
NaN,"Erie County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,459.306029,50.0,211.0,1602.0,2361.0,6019.0,19729.0,1481.0,341.0
NaN,"Los Angeles County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,444.800814,600.0,1976.0,18923.0,23057.0,49107.0,142604.0,40555.0,2210.0
NaN,"Dallas County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,442.965072,165.0,706.0,4889.0,5227.0,25141.0,59144.0,10235.0,692.0
NaN,"Bexar County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,431.060568,101.0,649.0,2038.0,5047.0,18580.0,69589.0,7155.0,336.0
NaN,"Tarrant County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,416.156389,73.0,687.0,2167.0,5028.0,16077.0,46906.0,4559.0,228.0
NaN,"Onondaga County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,374.903659,15.0,111.0,539.0,1091.0,2988.0,8553.0,592.0,63.0
NaN,"San Diego County, CA",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,368.672406,107.0,692.0,3200.0,7840.0,14076.0,43412.0,12136.0,346.0
NaN,"Monroe County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,356.854134,41.0,175.0,1011.0,1447.0,4968.0,16774.0,976.0,233.0
NaN,"Hillsborough County, FL",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,353.830740,53.0,187.0,1130.0,3200.0,7139.0,21548.0,1811.0,110.0
NaN,"Travis County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,345.420062,32.0,236.0,997.0,2607.0,8244.0,36913.0,2419.0,152.0
NaN,"Albany County, NY",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,330.678134,5.0,69.0,318.0,623.0,1497.0,7210.0,265.0,19.0
NaN,"Austin County, TX",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,194.127639,1.0,7.0,5.0,43.0,142.0,322.0,27.0,1.0

In [20]:
census_crime_merge.to_csv(os.path.join("..", "data", "census-csv", "merged_crime_census.csv"))

In [21]:
census_crime_merge.to_json(os.path.join("..", "data", "census-csv", "merged_crime_census.json"))