In [1]:
import pandas as pd
import os

In [2]:
#locate the 2010 census csv file last updated in 2017 that includes various demographic data points
census_file = os.path.join("..", "data", "census-csv", "acs2017_county_data.csv")

In [3]:
#read the census csv and create dataframe
census_df = pd.read_csv(census_file)
census_df.head()

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9

In [4]:
#print various elements from census files to ensure data transferred correctly
print(census_df.columns)
print(census_df.dtypes)
print(census_df.shape)

Index(['CountyId', 'State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'VotingAgeCitizen',
       'Income', 'IncomeErr', 'IncomePerCap', 'IncomePerCapErr', 'Poverty',
       'ChildPoverty', 'Professional', 'Service', 'Office', 'Construction',
       'Production', 'Drive', 'Carpool', 'Transit', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Employed', 'PrivateWork', 'PublicWork',
       'SelfEmployed', 'FamilyWork', 'Unemployment'],
      dtype='object')
CountyId              int64
State                object
County               object
TotalPop              int64
Men                   int64
Women                 int64
Hispanic            float64
White               float64
Black               float64
Native              float64
Asian               float64
Pacific             float64
VotingAgeCitizen      int64
Income                int64
IncomeErr             int64
IncomePerCap          int64
IncomePerCapErr       int64
Poverty             float64
ChildPoverty        float64
Professional        float64
Service             float64
Office              float64
Construction        float64
Production          float64
Drive               float64
Carpool             float64
Transit             float64
Walk                float64
OtherTransp         float64
WorkAtHome          float64
MeanCommute         float64
Employed              int64
PrivateWork         float64
PublicWork          float64
SelfEmployed        float64
FamilyWork          float64
Unemployment        float64
dtype: object
(3220, 37)

In [5]:
#remove any potential ending spaces in the census county column that will be joined with other data
census_df['County']=census_df['County'].apply(lambda x: x.strip())
census_df

,CountyId,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,...,Walk,OtherTransp,WorkAtHome,MeanCommute,Employed,PrivateWork,PublicWork,SelfEmployed,FamilyWork,Unemployment
0,1001,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,...,0.6,1.3,2.5,25.8,24112,74.1,20.2,5.6,0.1,5.2
1,1003,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,...,0.8,1.1,5.6,27.0,89527,80.7,12.9,6.3,0.1,5.5
2,1005,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,...,2.2,1.7,1.3,23.4,8878,74.1,19.1,6.5,0.3,12.4
3,1007,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,...,0.3,1.7,1.5,30.0,8171,76.0,17.4,6.3,0.3,8.2
4,1009,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,...,0.4,0.4,2.1,35.0,21380,83.9,11.9,4.0,0.1,4.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3215,72145,Puerto Rico,Vega Baja Municipio,54754,26269,28485,96.7,3.1,0.1,0.0,...,1.4,0.6,0.9,31.6,14234,76.2,19.3,4.3,0.2,16.8
3216,72147,Puerto Rico,Vieques Municipio,8931,4351,4580,95.7,4.0,0.0,0.0,...,5.0,0.0,1.7,14.9,2927,40.7,40.9,18.4,0.0,12.8
3217,72149,Puerto Rico,Villalba Municipio,23659,11510,12149,99.7,0.2,0.1,0.0,...,2.1,0.0,2.8,28.4,6873,59.2,30.2,10.4,0.2,24.8
3218,72151,Puerto Rico,Yabucoa Municipio,35025,16984,18041,99.9,0.1,0.0,0.0,...,1.4,1.8,0.1,30.5,7878,62.7,30.9,6.3,0.0,25.4
3219,72153,Puerto Rico,Yauco Municipio,37585,18052,19533,99.8,0.2,0.0,0.0,...,1.7,0.1,5.0,24.4,8995,66.4,28.7,5.0,0.0,24.0

In [6]:
#reduce the census data to specific columns needed for general county and demographic information
condensed_census = ['State', 'County', 'TotalPop', 'Men', 'Women', 'Hispanic',
       'White', 'Black', 'Native', 'Asian', 'Pacific', 'IncomePerCap', 'Professional', 'Walk', 'OtherTransp',
       'WorkAtHome', 'MeanCommute', 'Unemployment']
condensed_census_df = census_df[condensed_census]
condensed_census_df.head()

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,IncomePerCap,Professional,Walk,OtherTransp,WorkAtHome,MeanCommute,Unemployment
0,Alabama,Autauga County,55036,26899,28137,2.7,75.4,18.9,0.3,0.9,0.0,27824,35.3,0.6,1.3,2.5,25.8,5.2
1,Alabama,Baldwin County,203360,99527,103833,4.4,83.1,9.5,0.8,0.7,0.0,29364,35.7,0.8,1.1,5.6,27.0,5.5
2,Alabama,Barbour County,26201,13976,12225,4.2,45.7,47.8,0.2,0.6,0.0,17561,25.0,2.2,1.7,1.3,23.4,12.4
3,Alabama,Bibb County,22580,12251,10329,2.4,74.6,22.0,0.4,0.0,0.0,20911,24.4,0.3,1.7,1.5,30.0,8.2
4,Alabama,Blount County,57667,28490,29177,9.0,87.4,1.5,0.3,0.1,0.0,22021,28.5,0.4,0.4,2.1,35.0,4.9

In [10]:
#store states and counties for potential future use
#states = ["Texas", "Florida", "California", 'District of Columbia', 'New York']
#counties = ['Alameda County', 'Albany County','Austin County','Bexar County', 'Broward County',
            #'Dallas County', 'District of Columbia', 'Duval County', 'Erie County', 'Escambia County',
            #'Harris County', 'Hillsborough County', 'Los Angeles County', 'Monroe County', 'New York County',
           #'Pinellas Count', 'San Diego County','San Francisco County','Tarrant County']
#census_byAbnbstate = condensed_census_df.loc[condensed_census_df['State']=="Texas", "Florida", "California", 'District of Columbia', 'New York']

#further reduce latest condensed census to specific states of interest
census_byAbnbstate = condensed_census_df[(condensed_census_df['State'] == "Texas")| 
                                         (condensed_census_df['State'] =="Florida")| 
                                         (condensed_census_df['State'] =="California")|
                                         (condensed_census_df['State'] =='District of Columbia')|
                                         (condensed_census_df['State'] == 'New York')]
census_byAbnbstate

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,IncomePerCap,Professional,Walk,OtherTransp,WorkAtHome,MeanCommute,Unemployment
186,California,Alameda County,1629615,799649,829966,22.5,32.2,10.7,0.3,28.7,0.8,41363,48.0,3.7,3.6,6.0,32.5,6.0
187,California,Alpine County,1203,664,539,9.7,64.6,1.5,20.6,0.7,0.0,27448,38.2,9.1,1.6,14.0,21.9,14.6
188,California,Amador County,37306,20005,17301,13.2,79.3,2.0,0.7,1.5,0.2,29628,32.7,2.5,1.1,6.4,32.0,9.3
189,California,Butte County,225207,111587,113620,15.7,72.9,1.5,0.7,4.4,0.2,26304,35.9,3.2,3.9,5.7,20.1,9.1
190,California,Calaveras County,45057,22292,22765,11.5,82.0,0.6,0.9,1.2,0.5,31652,35.6,1.2,0.6,8.3,35.5,7.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2772,Texas,Wood County,43315,21523,21792,9.6,83.2,5.5,0.6,0.1,0.1,25955,28.7,2.5,1.0,5.6,30.2,7.8
2773,Texas,Yoakum County,8481,4286,4195,65.0,33.2,0.0,0.2,0.0,0.0,23681,21.8,3.7,0.2,1.3,16.2,7.5
2774,Texas,Young County,18166,8922,9244,18.1,78.8,1.5,0.5,0.4,0.0,25661,31.5,0.6,1.4,6.1,15.3,4.5
2775,Texas,Zapata County,14415,7190,7225,94.1,5.2,0.0,0.0,0.7,0.0,17817,17.7,4.4,0.6,2.0,18.2,12.4
2776,Texas,Zavala County,12152,6163,5989,93.6,5.4,0.5,0.1,0.0,0.0,13105,29.0,2.1,4.2,5.4,13.7,10.1

In [11]:
#["Bexar", "Travis", "Tarrant", "Dallas", "Harris", "Alameda", "Los Angeles", 
#"San Francisco", "San Diego", "Broward", "Duval", "Hillsborough", 
#"Escambia", "Pinellas", "New York", "Kings", "Erie", "Monroe County", 
#"Albany", "Onondaga", "District of Columbia"]
census_byAbnbcounty = census_byAbnbstate[(census_byAbnbstate['County'] == 'Alameda County')| 
                                         (census_byAbnbstate['County'] =='Albany County')| 
                                         (census_byAbnbstate['County'] =='Austin County')|
                                         (census_byAbnbstate['County'] =='Bexar County')|
                                         (census_byAbnbstate['County'] =='Broward County' )|
                                        (census_byAbnbstate['County'] =='Dallas County')|
                                        (census_byAbnbstate['County'] =='District of Columbia')|
                                        (census_byAbnbstate['County'] =='Duval County')|
                                        (census_byAbnbstate['County'] =='Erie County')|
                                        (census_byAbnbstate['County'] =='Escambia County')|
                                        (census_byAbnbstate['County'] =='Harris County')|
                                        (census_byAbnbstate['County'] =='Hillsborough County')|
                                        (census_byAbnbstate['County'] =='Los Angeles County')|
                                        (census_byAbnbstate['County'] =='Monroe County')|
                                        (census_byAbnbstate['County'] =='New York County')|
                                        (census_byAbnbstate['County'] =='Pinellas County')|
                                        (census_byAbnbstate['County'] =='San Diego County')|
                                        (census_byAbnbstate['County'] =='San Francisco County')|
                                        (census_byAbnbstate['County'] =='Tarrant County')|
                                        (census_byAbnbstate['County'] =='Travis County')|
                                        (census_byAbnbstate['County'] =='Onondaga County')]
                                        
census_byAbnbcounty.head()

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,IncomePerCap,Professional,Walk,OtherTransp,WorkAtHome,MeanCommute,Unemployment
186,California,Alameda County,1629615,799649,829966,22.5,32.2,10.7,0.3,28.7,0.8,41363,48.0,3.7,3.6,6.0,32.5,6.0
204,California,Los Angeles County,10105722,4979641,5126081,48.4,26.5,7.9,0.2,14.3,0.2,30798,36.4,2.7,2.3,5.3,30.9,7.8
222,California,San Diego County,3283665,1651147,1632518,33.4,46.2,4.7,0.4,11.5,0.4,34350,41.3,2.9,2.2,7.0,25.7,7.1
223,California,San Francisco County,864263,440633,423630,15.3,40.8,5.1,0.2,33.9,0.3,59508,55.0,11.1,7.1,6.7,32.8,5.4
319,District of Columbia,District of Columbia,672391,319046,353345,10.7,36.0,46.9,0.2,3.7,0.0,50832,61.7,13.2,6.2,5.7,30.0,8.0

In [12]:
#export condensed csv to a csv for future merge
census_byAbnbcounty.to_csv(os.path.join("..", "data", "census-csv", "census_bycounty.csv"))

In [ ]:
############break

In [17]:
#locate file with various crime information
crime_file = os.path.join("..", "data", "crime_county-csv", "crime_data_w_population_and_crime_rate.csv")

In [18]:
#read the crime csv file and store in data frame
crime_df = pd.read_csv(crime_file)
crime_df.head()

,county_name,crime_rate_per_100000,index,EDITION,PART,IDNO,CPOPARST,CPOPCRIM,AG_ARRST,AG_OFF,...,RAPE,ROBBERY,AGASSLT,BURGLRY,LARCENY,MVTHEFT,ARSON,population,FIPS_ST,FIPS_CTY
0,"St. Louis city, MO",1791.995377,1,1,4,1612,318667,318667,15,15,...,200,1778,3609,4995,13791,3543,464,318416,29,510
1,"Crittenden County, AR",1754.914968,2,1,4,130,50717,50717,4,4,...,38,165,662,1482,1753,189,28,49746,5,35
2,"Alexander County, IL",1664.700485,3,1,4,604,8040,8040,2,2,...,2,5,119,82,184,12,2,7629,17,3
3,"Kenedy County, TX",1456.310680,4,1,4,2681,444,444,1,1,...,3,1,2,5,4,4,0,412,48,261
4,"De Soto Parish, LA",1447.402430,5,1,4,1137,26971,26971,3,3,...,4,17,368,149,494,60,0,27083,22,31

In [19]:
#print various data columns to verify information populated correctly and data types
print(crime_df.columns)
print(crime_df.dtypes)
print(crime_df.shape)

Index(['county_name', 'crime_rate_per_100000', 'index', 'EDITION', 'PART',
       'IDNO', 'CPOPARST', 'CPOPCRIM', 'AG_ARRST', 'AG_OFF', 'COVIND', 'INDEX',
       'MODINDX', 'MURDER', 'RAPE', 'ROBBERY', 'AGASSLT', 'BURGLRY', 'LARCENY',
       'MVTHEFT', 'ARSON', 'population', 'FIPS_ST', 'FIPS_CTY'],
      dtype='object')
county_name               object
crime_rate_per_100000    float64
index                      int64
EDITION                    int64
PART                       int64
IDNO                       int64
CPOPARST                   int64
CPOPCRIM                   int64
AG_ARRST                   int64
AG_OFF                     int64
COVIND                   float64
INDEX                      int64
MODINDX                    int64
MURDER                     int64
RAPE                       int64
ROBBERY                    int64
AGASSLT                    int64
BURGLRY                    int64
LARCENY                    int64
MVTHEFT                    int64
ARSON                      int64
population                 int64
FIPS_ST                    int64
FIPS_CTY                   int64
dtype: object
(3136, 24)

In [20]:
#reduce crime data into specific columns that focus on specific crime
condensed_crime = ['county_name', 'crime_rate_per_100000', 'MURDER', 'RAPE', 'ROBBERY', 'AGASSLT', 'BURGLRY', 'LARCENY',
       'MVTHEFT', 'ARSON']
condensed_crime_df = crime_df[condensed_crime]
condensed_crime_df.head()

,county_name,crime_rate_per_100000,MURDER,RAPE,ROBBERY,AGASSLT,BURGLRY,LARCENY,MVTHEFT,ARSON
0,"St. Louis city, MO",1791.995377,119,200,1778,3609,4995,13791,3543,464
1,"Crittenden County, AR",1754.914968,8,38,165,662,1482,1753,189,28
2,"Alexander County, IL",1664.700485,1,2,5,119,82,184,12,2
3,"Kenedy County, TX",1456.310680,0,3,1,2,5,4,4,0
4,"De Soto Parish, LA",1447.402430,3,4,17,368,149,494,60,0

In [21]:
#rename the condensed data frame columns to correct casing and spelling
condensed_crime_df.rename(columns={'county_name' : "County", 'crime_rate_per_100000' : 'Crime_RatePer100K', 
                                   'MURDER': 'Murder', 'RAPE': 'Rape', 'ROBBERY' : 'Robbery', 'AGASSLT' : 'Agg.Assault',
                                   'BURGLRY': 'Burglary', 'LARCENY':'Larceny', 'MVTHEFT': 'MotorVeh Theft', 'ARSON':'Arson', 
                                   'population' : 'Population'}, inplace =True)

condensed_crime_df.head()

C:\Users\brand\anaconda3\lib\site-packages\pandas\core\frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,County,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
0,"St. Louis city, MO",1791.995377,119,200,1778,3609,4995,13791,3543,464
1,"Crittenden County, AR",1754.914968,8,38,165,662,1482,1753,189,28
2,"Alexander County, IL",1664.700485,1,2,5,119,82,184,12,2
3,"Kenedy County, TX",1456.310680,0,3,1,2,5,4,4,0
4,"De Soto Parish, LA",1447.402430,3,4,17,368,149,494,60,0

In [22]:
#reduce crime data by counties of interest in the states of data search by county and state
crime_byAbnbcounty = condensed_crime_df[(condensed_crime_df['County'] == 'Alameda County, CA')| 
                                         (condensed_crime_df['County'] =='Albany County, NY')| 
                                         (condensed_crime_df['County'] =='Austin County, TX')|
                                         (condensed_crime_df['County'] =='Bexar County, TX')|
                                         (condensed_crime_df['County'] =='Broward County, FL' )|
                                        (condensed_crime_df['County'] =='Dallas County, TX')|
                                        (condensed_crime_df['County'] =='District of Columbia, DC')|
                                        (condensed_crime_df['County'] =='Duval County, FL')|
                                        (condensed_crime_df['County'] =='Erie County, NY')|
                                        (condensed_crime_df['County'] =='Escambia County, FL')|
                                        (condensed_crime_df['County'] =='Harris County, TX')|
                                        (condensed_crime_df['County'] =='Hillsborough County, FL')|
                                        (condensed_crime_df['County'] =='Los Angeles County, CA')|
                                        (condensed_crime_df['County'] =='Monroe County, NY')|
                                        (condensed_crime_df['County'] =='New York County, NY')|
                                        (condensed_crime_df['County'] =='Pinellas County, FL')|
                                        (condensed_crime_df['County'] =='San Diego County, CA')|
                                        (condensed_crime_df['County'] =='San Francisco County, CA')|
                                        (condensed_crime_df['County'] =='Tarrant County, TX')|
                                        (condensed_crime_df['County'] =='Travis County, TX')|
                                        (condensed_crime_df['County'] =='Onondaga County, NY')]
                                        
crime_byAbnbcounty.head()

,County,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
9,"District of Columbia, DC",1216.801325,88,236,4037,3505,3519,23575,3663,51
57,"Escambia County, FL",798.516760,22,162,502,1756,3899,9920,680,52
71,"Alameda County, CA",753.693574,153,477,6220,5050,13245,35841,13044,337
90,"San Francisco County, CA",701.421710,69,110,3554,2141,5401,29256,5381,211
93,"Harris County, TX",696.103834,307,1143,12449,16290,43644,114208,20829,1153

In [23]:
#split the condensed county datafram by county column to remove the state to ensure merge with census data is by county so spelling must be exact
crime_byAbnbcounty['County'] = crime_byAbnbcounty['County'].apply(lambda x: pd.Series(x.split(',')))
crime_byAbnbcounty

<ipython-input-23-f247292aa47b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  crime_byAbnbcounty['County'] = crime_byAbnbcounty['County'].apply(lambda x: pd.Series(x.split(',')))

,County,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
9,District of Columbia,1216.801325,88,236,4037,3505,3519,23575,3663,51
57,Escambia County,798.516760,22,162,502,1756,3899,9920,680,52
71,Alameda County,753.693574,153,477,6220,5050,13245,35841,13044,337
90,San Francisco County,701.421710,69,110,3554,2141,5401,29256,5381,211
93,Harris County,696.103834,307,1143,12449,16290,43644,114208,20829,1153
130,New York County,634.009343,81,227,3932,6070,3623,22730,1592,0
142,Duval County,621.546416,94,355,1436,3621,8025,27335,1712,96
233,Pinellas County,550.671225,44,361,1206,3505,7392,24499,1755,167
352,Broward County,470.948052,80,401,3408,4771,17400,45279,4320,180
370,Erie County,459.306029,50,211,1602,2361,6019,19729,1481,341
396,Los Angeles County,444.800814,600,1976,18923,23057,49107,142604,40555,2210
404,Dallas County,442.965072,165,706,4889,5227,25141,59144,10235,692
432,Bexar County,431.060568,101,649,2038,5047,18580,69589,7155,336
467,Tarrant County,416.156389,73,687,2167,5028,16077,46906,4559,228
586,Onondaga County,374.903659,15,111,539,1091,2988,8553,592,63
605,San Diego County,368.672406,107,692,3200,7840,14076,43412,12136,346
652,Monroe County,356.854134,41,175,1011,1447,4968,16774,976,233
661,Hillsborough County,353.830740,53,187,1130,3200,7139,21548,1811,110
687,Travis County,345.420062,32,236,997,2607,8244,36913,2419,152
749,Albany County,330.678134,5,69,318,623,1497,7210,265,19
1497,Austin County,194.127639,1,7,5,43,142,322,27,1

In [24]:
#output crime data in csv for future use
crime_byAbnbcounty.to_csv(os.path.join("..", "data", "census-csv", "crime_bycounty.csv"))

In [ ]:
##################break

In [25]:
#merge the condensed census and crime csv files on county to to add crime information to census data
census_crime_merge = pd.merge(census_byAbnbcounty,crime_byAbnbcounty, on="County", how ="outer" )
census_crime_merge

,State,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,...,Unemployment,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
0,California,Alameda County,1629615,799649,829966,22.5,32.2,10.7,0.3,28.7,...,6.0,753.693574,153,477,6220,5050,13245,35841,13044,337
1,California,Los Angeles County,10105722,4979641,5126081,48.4,26.5,7.9,0.2,14.3,...,7.8,444.800814,600,1976,18923,23057,49107,142604,40555,2210
2,California,San Diego County,3283665,1651147,1632518,33.4,46.2,4.7,0.4,11.5,...,7.1,368.672406,107,692,3200,7840,14076,43412,12136,346
3,California,San Francisco County,864263,440633,423630,15.3,40.8,5.1,0.2,33.9,...,5.4,701.421710,69,110,3554,2141,5401,29256,5381,211
4,District of Columbia,District of Columbia,672391,319046,353345,10.7,36.0,46.9,0.2,3.7,...,8.0,1216.801325,88,236,4037,3505,3519,23575,3663,51
5,Florida,Broward County,1890416,920265,970151,28.4,38.2,27.4,0.2,3.5,...,7.6,470.948052,80,401,3408,4771,17400,45279,4320,180
6,Florida,Duval County,912043,442115,469928,9.0,54.1,29.3,0.2,4.6,...,7.4,621.546416,94,355,1436,3621,8025,27335,1712,96
7,Texas,Duval County,11434,5891,5543,89.3,9.0,1.4,0.0,0.3,...,13.6,621.546416,94,355,1436,3621,8025,27335,1712,96
8,Florida,Escambia County,309924,153834,156090,5.5,64.8,21.6,0.4,2.8,...,7.2,798.516760,22,162,502,1756,3899,9920,680,52
9,Florida,Hillsborough County,1351087,658639,692448,27.4,50.3,15.5,0.2,3.9,...,6.8,353.830740,53,187,1130,3200,7139,21548,1811,110
10,Florida,Monroe County,76745,40218,36527,23.5,67.3,6.7,0.1,1.2,...,3.7,356.854134,41,175,1011,1447,4968,16774,976,233
11,New York,Monroe County,748680,361649,387031,8.3,71.0,14.5,0.2,3.6,...,6.6,356.854134,41,175,1011,1447,4968,16774,976,233
12,Florida,Pinellas County,949842,456017,493825,9.2,74.7,10.0,0.2,3.3,...,6.4,550.671225,44,361,1206,3505,7392,24499,1755,167
13,New York,Albany County,308580,149287,159293,5.7,73.0,11.7,0.1,6.4,...,5.3,330.678134,5,69,318,623,1497,7210,265,19
14,New York,Erie County,923995,447024,476971,5.2,76.0,13.0,0.4,3.4,...,5.5,459.306029,50,211,1602,2361,6019,19729,1481,341
15,New York,New York County,1653877,782142,871735,26.1,46.8,12.5,0.1,11.9,...,6.2,634.009343,81,227,3932,6070,3623,22730,1592,0
16,New York,Onondaga County,467669,225685,241984,4.7,77.1,10.7,0.5,3.9,...,6.4,374.903659,15,111,539,1091,2988,8553,592,63
17,Texas,Austin County,29292,14474,14818,25.9,63.3,8.9,0.0,0.2,...,5.4,194.127639,1,7,5,43,142,322,27,1
18,Texas,Bexar County,1892004,932577,959427,59.8,28.4,7.0,0.2,2.6,...,6.1,431.060568,101,649,2038,5047,18580,69589,7155,336
19,Texas,Dallas County,2552213,1257751,1294462,39.6,30.2,22.1,0.2,6.0,...,5.9,442.965072,165,706,4889,5227,25141,59144,10235,692
20,Texas,Harris County,4525519,2251060,2274459,42.2,30.6,18.5,0.2,6.8,...,6.4,696.103834,307,1143,12449,16290,43644,114208,20829,1153
21,Texas,Tarrant County,1983675,971142,1012533,28.2,48.3,15.6,0.3,5.1,...,5.4,416.156389,73,687,2167,5028,16077,46906,4559,228
22,Texas,Travis County,1176584,593319,583265,33.9,49.3,7.9,0.2,6.3,...,4.5,345.420062,32,236,997,2607,8244,36913,2419,152

In [26]:
#reset the index of data to state
census_crime_merge.set_index('State')

,County,TotalPop,Men,Women,Hispanic,White,Black,Native,Asian,Pacific,...,Unemployment,Crime_RatePer100K,Murder,Rape,Robbery,Agg.Assault,Burglary,Larceny,MotorVeh Theft,Arson
State,,,,,,,,,,,,,,,,,,,,,
California,Alameda County,1629615,799649,829966,22.5,32.2,10.7,0.3,28.7,0.8,...,6.0,753.693574,153,477,6220,5050,13245,35841,13044,337
California,Los Angeles County,10105722,4979641,5126081,48.4,26.5,7.9,0.2,14.3,0.2,...,7.8,444.800814,600,1976,18923,23057,49107,142604,40555,2210
California,San Diego County,3283665,1651147,1632518,33.4,46.2,4.7,0.4,11.5,0.4,...,7.1,368.672406,107,692,3200,7840,14076,43412,12136,346
California,San Francisco County,864263,440633,423630,15.3,40.8,5.1,0.2,33.9,0.3,...,5.4,701.421710,69,110,3554,2141,5401,29256,5381,211
District of Columbia,District of Columbia,672391,319046,353345,10.7,36.0,46.9,0.2,3.7,0.0,...,8.0,1216.801325,88,236,4037,3505,3519,23575,3663,51
Florida,Broward County,1890416,920265,970151,28.4,38.2,27.4,0.2,3.5,0.0,...,7.6,470.948052,80,401,3408,4771,17400,45279,4320,180
Florida,Duval County,912043,442115,469928,9.0,54.1,29.3,0.2,4.6,0.1,...,7.4,621.546416,94,355,1436,3621,8025,27335,1712,96
Texas,Duval County,11434,5891,5543,89.3,9.0,1.4,0.0,0.3,0.0,...,13.6,621.546416,94,355,1436,3621,8025,27335,1712,96
Florida,Escambia County,309924,153834,156090,5.5,64.8,21.6,0.4,2.8,0.1,...,7.2,798.516760,22,162,502,1756,3899,9920,680,52
Florida,Hillsborough County,1351087,658639,692448,27.4,50.3,15.5,0.2,3.9,0.1,...,6.8,353.830740,53,187,1130,3200,7139,21548,1811,110
Florida,Monroe County,76745,40218,36527,23.5,67.3,6.7,0.1,1.2,0.0,...,3.7,356.854134,41,175,1011,1447,4968,16774,976,233
New York,Monroe County,748680,361649,387031,8.3,71.0,14.5,0.2,3.6,0.0,...,6.6,356.854134,41,175,1011,1447,4968,16774,976,233
Florida,Pinellas County,949842,456017,493825,9.2,74.7,10.0,0.2,3.3,0.1,...,6.4,550.671225,44,361,1206,3505,7392,24499,1755,167
New York,Albany County,308580,149287,159293,5.7,73.0,11.7,0.1,6.4,0.0,...,5.3,330.678134,5,69,318,623,1497,7210,265,19
New York,Erie County,923995,447024,476971,5.2,76.0,13.0,0.4,3.4,0.0,...,5.5,459.306029,50,211,1602,2361,6019,19729,1481,341
New York,New York County,1653877,782142,871735,26.1,46.8,12.5,0.1,11.9,0.0,...,6.2,634.009343,81,227,3932,6070,3623,22730,1592,0
New York,Onondaga County,467669,225685,241984,4.7,77.1,10.7,0.5,3.9,0.0,...,6.4,374.903659,15,111,539,1091,2988,8553,592,63
Texas,Austin County,29292,14474,14818,25.9,63.3,8.9,0.0,0.2,0.0,...,5.4,194.127639,1,7,5,43,142,322,27,1
Texas,Bexar County,1892004,932577,959427,59.8,28.4,7.0,0.2,2.6,0.1,...,6.1,431.060568,101,649,2038,5047,18580,69589,7155,336
Texas,Dallas County,2552213,1257751,1294462,39.6,30.2,22.1,0.2,6.0,0.0,...,5.9,442.965072,165,706,4889,5227,25141,59144,10235,692
Texas,Harris County,4525519,2251060,2274459,42.2,30.6,18.5,0.2,6.8,0.1,...,6.4,696.103834,307,1143,12449,16290,43644,114208,20829,1153
Texas,Tarrant County,1983675,971142,1012533,28.2,48.3,15.6,0.3,5.1,0.2,...,5.4,416.156389,73,687,2167,5028,16077,46906,4559,228
Texas,Travis County,1176584,593319,583265,33.9,49.3,7.9,0.2,6.3,0.0,...,4.5,345.420062,32,236,997,2607,8244,36913,2419,152

In [27]:
#output of merge data into csv to use in sql table
census_crime_merge.to_csv(os.path.join("..", "data", "census-csv", "merged_crime_census.csv"))

In [28]:
#output of data in json in the event it is needed to be merged with API json data
census_crime_merge.to_json(os.path.join("..", "data", "census-csv", "merged_crime_census.json"))